# /etc/nginx/sites-available/maze.duruwap.com
server {
    listen 80;
    server_name maze.duruwap.com;
    location /.well-known/acme-challenge/ { root /var/www/html; }
    location / { return 301 https://$host$request_uri; }
}

server {
    listen 443 ssl http2;
    server_name maze.duruwap.com;

    ssl_certificate     /etc/letsencrypt/live/maze.duruwap.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/maze.duruwap.com/privkey.pem;

    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;

    location /static/ {
        alias /scsrun/app/maze-in-dungeon/static/;
        expires 1h;
        add_header Cache-Control "public";
    }

    location / {
        proxy_pass http://127.0.0.1:15003;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 30s;
    }
}
